apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    configmanagement.gke.io/managed: 'disabled'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lukeaddison785@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio
