apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-lukeaddison-co-uk
  namespace: istio-system
  annotations:
    configmanagement.gke.io/managed: 'disabled'
spec:
  secretName: jenkins-lukeaddison-co-uk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jenkins.lukeaddison.co.uk
