apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-service-account
  namespace: istio-system
  labels:
    app: istiod
    release: istio
  annotations:
    configmanagement.gke.io/managed: 'disabled'
