---
# Source: jenkins/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
data:
  apply_config.sh: |-
    set -e
    echo "disable Setup Wizard"
    # Prevent Setup Wizard when JCasC is enabled
    echo $JENKINS_VERSION > /var/jenkins_home/jenkins.install.UpgradeWizard.state
    echo $JENKINS_VERSION > /var/jenkins_home/jenkins.install.InstallUtil.lastExecVersion
    echo "remove all plugins from shared volume"
    # remove all plugins from shared volume
    rm -rf /var/jenkins_home/plugins/*
    echo "download plugins"
    # Install missing plugins
    cp /var/jenkins_config/plugins.txt /var/jenkins_home;
    rm -rf /usr/share/jenkins/ref/plugins/*.lock
    version () { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
    if [ -f "/usr/share/jenkins/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt";
    else
      /usr/local/bin/install-plugins.sh `echo $(cat /var/jenkins_home/plugins.txt)`;
    fi
    echo "copy plugins to shared volume"
    # Copy plugins to shared volume
    yes n | cp -i /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins/;
    echo "finished initialization"
  plugins.txt: |-
    kubernetes:1.27.6
    workflow-aggregator:2.6
    git:4.5.2
    configuration-as-code:1.47
    ghprb:1.42.0
    github:1.33.0
    pipeline-model-definition:1.8.4
    pipeline-stage-view:2.19
    credentials:2.3.15
    pipeline-input-step:2.12
    pipeline-graph-analysis:1.10
    pipeline-rest-api:2.19
    ssh-credentials:1.18.1
    jsch:0.1.55.2
    git-client:3.6.0
    authentication-tokens:1.4
    plain-credentials:1.7
    kubernetes-credentials:0.8.0
    git-server:1.9
    workflow-cps-global-lib:2.17
    credentials-binding:1.24
    pipeline-model-extensions:1.8.3
    github-branch-source:2.10.1
    pipeline-utility-steps:2.6.1
