apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generate
  namespace: jenkins
  annotations:
    configmanagement.gke.io/managed: 'disabled'
rules:
  - apiGroups:
      - ""
    resourceNames:
      - git-auth
    resources:
      - secrets
    verbs:
      - get
