apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    configmanagement.gke.io/managed: 'disabled'
spec:
  hosts:
    - jenkins.lukeaddison.co.uk
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - port: 8443
      route:
        - destination:
            host: jenkins
