apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jenkins-lukeaddison-co-uk
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lukeaddison785@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - jenkins.lukeaddison.co.uk
      http01:
        ingress:
          class: istio
