# Source: nginx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  annotations:
    configmanagement.gke.io/managed: 'disabled'
spec:
  selector:
    app: nginx
  ports:
    - port: 80
